### ISSUE TITLE
Expand `shell` environment variables in docker compose

### ISSUE THREAD

**Issue by zhukovdm** [zhukovdm/smartwalk#9]
The construction below injects environment variables into a container. However, these variables are not visible in the file, and ${VAR} ends up being undefined. The true value of this particular variable is defined in the `./infra/.env` file, while variables for other services are defined in the `compose` file.

```
services:
  routing:
    environment:
      - REGION_FILE=...
    entrypoint: ...${REGION_FILE}...
```
